#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

HISTSIZE=50000
SAVEHIST=50000

setopt HIST_IGNORE_DUPS

# Exports
source ~/.exports

# Functions
source ~/.functions

# Aliases
source ~/.aliases
